name: kyma function deployment

on:
  push:
    branches:
    - master
    paths:
    - 'lambdas/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master
    - name: Get Changes
      uses: lots0logs/gh-action-get-changed-files@2.0.5
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: list changed files  
      run: |
        echo "----files----"
        cat ${HOME}/files.json
        echo "----added----"
        cat ${HOME}/files_added.json
        echo "----modfied----"
        cat ${HOME}/files_modified.json
        echo "----deleted----"
        cat ${HOME}/files_deleted.json
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - run: npm install  
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        files: lambdas/*/*.js
    - name: Generate the deployment yaml
      run: |
        ROOTDIR=$HOME/files.json npm run deploymentYaml
    - name: Deploy function to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ./build/deployment.yaml
    - name: Save deployment result artifact  
      uses: actions/upload-artifact@v1
      with:
        name: deployment.yaml
        path: ./build/deployment.yaml

